### ISSUE TITLE
Haxelib says latest version is 1.0.2-alpha, but 0.4.0 was published more recently?

### ISSUE THREAD

**Issue by joshtynjala** [HaxeFoundation/crypto#18]
It appears that you went backwards in version numbering, which is potentially confusing and dangerous (especially for an encryption library, which needs to be held to a high standard, considering the security implications). Luckily, it seems that `haxelib install crypto` installs version 0.4.0 correctly, but the Haxelib website still says that 1.0.2-alpha is the newest version (which it isn't, obviously).

I hope that you will consider making the next published version be 1.5.0 or 2.0.0 (or anything higher than 1.0.2) instead of 0.5.0.

**Comment by flashultra** [comment]
Yes, the next version should be higher than 1.0.2 
However, I did not release official version 1.0.0 , because there are some annoying bugs and some failed Hashlink tests:
https://github.com/HaxeFoundation/haxe/issues/9415
https://github.com/HaxeFoundation/haxe/issues/7533
My wish was those bugs to be fixed before version 1, but this probably won't happen soon, so the next version shouldn't be > 1.0.2

**Comment by flashultra** [comment]
Version 1.0.3  was published.
