### ISSUE TITLE
PHP test failures

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/crypto#26]
Tests currently fail on PHP. Can we make them not fail on PHP?

**Comment by flashultra** [comment]
If I remember correctly, the problem with php tests come from this issue in Haxe ( https://github.com/HaxeFoundation/haxe/issues/7533 )
There are at least two solutions: 
 1) Proper fix in Haxe 
 2) Using a hack in the crypto lib to show the correct behaviour.

Regarding 1) , will this be fixed in Haxe std?

**Comment by Simn** [comment]
The Haxe issue seems controversial, it's not clear if `Int` should specify this kind of overflow behavior. So it would be better to address this here.
