### ISSUE TITLE
Publish on haxelib

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/crypto#8]
It would be nice to publish this to haxelib. It'll probably also need a haxelib.json file.

**Comment by flashultra** [comment]
There are some problems which should be fixed before that, but you can use it ( for most targets).
The problems for which I ( and Travis ) know are :
 - Hashlink - BCrypt is not working
- PHP - overflow problem ( https://github.com/HaxeFoundation/haxe/issues/7533 )
- Flash - Pbkdf2 ( is too slow  and not usable at all ) 

Also BCrypt is too slow ,so I should replace all Array with Vector ,which is not the best solution for the moment because  JS target give worst results  when using vector copy() method.

**Comment by flashultra** [comment]
Ok, so I published alpha release . Hashlink works locally, but give error on Travis. For php will fix it in other releases . 
Let see whether anyone will report other problems.
